version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1104
      - DATABASE_NAME=fastAPI
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=3de4c95a32928da15d97fa58144e43f07e610f1e440d490d8ba8a458a3be3bbb
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: /usr/src/app/entrypoint.sh
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1104
      - POSTGRES_DB=fastAPI
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: